name: Build Rstudio Docker Image CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r_version: [ 4.0.4 ]
    steps:
    - uses: actions/checkout@v2
  
    - name: Branch name
      run: echo running on branch ${{ github.ref_name }} for ${{ matrix.r_version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: set lower case repo name (Bug when repository is in UPPERCASE)
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

          
    - name: Open issue to change sspcloud formations
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cat << EOF > body.txt
        Nouvelle image :
        
        $IMAGE_REPOSITORY_URL
        
        Se rendre :
          
        https://github.com/InseeFrLab/www.sspcloud.fr/blob/main/src/lib/educationalResources/educationalResources.ts
        
        Puis \`Ctrl+Shift+f\` pour rechercher/remplacer
        
        Copier/coller : 
        
        \`/(datalab.sspcloud.fr.*)${GITHUB_REPOSITORY#*/}-([\w\d\.:]*)/\` 
          
        Faire \`Entrer\`
        
        Remplacer le with par : 
        
        \`\$1${GITHUB_REPOSITORY#*/}-$R_VERSION_SHA\`
        
        Faire \`Entrer\` et choisir \`yes\`
        
        EOF
        gh issue create \
          --title "Mise à jour image docker (formation sspcloud)" \
          --body-file body.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY_URL: ghcr.io/${{ env.IMAGE_REPOSITORY }}-${{ matrix.r_version }}:${{ github.sha }}
        R_VERSION_SHA: ${{ matrix.r_version }}:${{ github.sha }}
